name:                 z-regexp-dfa-z-regexp-dfa-lib
version:              0.1.0.0
package-name:         regexp-dfa
lib-name:             regexp-dfa-lib
id:                   regexp-dfa-0.1.0.0-inplace-regexp-dfa-lib
key:                  regexp-dfa-0.1.0.0-inplace-regexp-dfa-lib
abi:                  inplace
exposed-modules:
    BoundedLang DFA DFFile Matcher NFA Parser Parsing Types Unparser
    Visualise

import-dirs:
    C:\Users\malco\Documents\Portfolio\RegexpDfa\dist-newstyle\build\x86_64-windows\ghc-9.6.7\regexp-dfa-0.1.0.0\l\regexp-dfa-lib\build\regexp-dfa-lib

library-dirs:
    C:\Users\malco\Documents\Portfolio\RegexpDfa\dist-newstyle\build\x86_64-windows\ghc-9.6.7\regexp-dfa-0.1.0.0\l\regexp-dfa-lib\build\regexp-dfa-lib
    C:\ghcup\msys64\mingw64\lib

library-dirs-static:
    C:\Users\malco\Documents\Portfolio\RegexpDfa\dist-newstyle\build\x86_64-windows\ghc-9.6.7\regexp-dfa-0.1.0.0\l\regexp-dfa-lib\build\regexp-dfa-lib
    C:\ghcup\msys64\mingw64\lib

dynamic-library-dirs:
    C:\Users\malco\Documents\Portfolio\RegexpDfa\dist-newstyle\build\x86_64-windows\ghc-9.6.7\regexp-dfa-0.1.0.0\l\regexp-dfa-lib\build\regexp-dfa-lib
    C:\ghcup\msys64\mingw64\lib

data-dir:             C:\Users\malco\Documents\Portfolio\RegexpDfa\.
hs-libraries:         HSregexp-dfa-0.1.0.0-inplace-regexp-dfa-lib
include-dirs:         C:\ghcup\msys64\mingw64\include
depends:              base-4.18.3.0 containers-0.6.7
haddock-interfaces:
    C:\Users\malco\Documents\Portfolio\RegexpDfa\dist-newstyle\build\x86_64-windows\ghc-9.6.7\regexp-dfa-0.1.0.0\l\regexp-dfa-lib\doc\html\regexp-dfa\regexp-dfa.haddock

haddock-html:
    C:\Users\malco\Documents\Portfolio\RegexpDfa\dist-newstyle\build\x86_64-windows\ghc-9.6.7\regexp-dfa-0.1.0.0\l\regexp-dfa-lib\doc\html\regexp-dfa
